import Head from "next/head";
import Image from "next/image";
import styles from "../styles/index.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Em Breve</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <h2>em breve novidades</h2>
        <a
          href="https://forms.office.com/r/VTxxF97D0J"
          target="_blank"
          rel="noopener noreferrer"
        >
          envie uma mensagem
        </a>
        <a
          href="https://dev.rodneyrinaldi.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          <div>
            <Image
              src="/logo.svg"
              alt="rodneyrinaldi logo"
              width={28}
              height={28}
            />
          </div>
        </a>
      </div>
    </div>
  );
}
